### ISSUE TITLE
Plugin does not remember password in 0.7.7

### ISSUE THREAD

**Issue by kwestvelt** [groboclown/p4ic4idea#109]
![password](https://cloud.githubusercontent.com/assets/12437972/13782049/23b48bc6-ea8b-11e5-9ab2-003720902d35.PNG)

I am prompted to re-enter my password every couple minutes even though it is already entered correctly.

**Comment by kcwill2** [comment]
I am seeing this as well.

**Comment by groboclown** [comment]
Thanks for the feedback on this issue.

This has been a lingering issue that I've been investigating for a while now.  The Perforce server is sending back an unauthorized error when the plugin tries to authenticate itself, even with valid permissions.  I think that the underlying issue is that something is causing the plugin to attempt to authenticate itself after it's already been authenticated, and the Perforce server doesn't like the double authentication on a single open connection.

**Comment by ghostofcain** [comment]
Same issue here and it's extremely annoying. Event forcing it to go offline doesn't help and it keeps popping up everytime I change a file. Hopefully it can be fixed soon.

**Comment by groboclown** [comment]
It looks like the issue is that the Perforce server is rejecting multiple, simultaneous login attempts from the same host - at least half of the requests result in the server returning "password is invalid" or "password is unset".  When I force the connect and login calls to be serialized, it seems to work without issue.

I'll play with this a bit more, to see if this really does solve the issue, but preliminary results look promising.

**Comment by groboclown** [comment]
The latest release (0.7.8) contains some work-arounds for this issue, but it's still a strange problem.  I'm going to start asking the Perforce folks what's going on to better understand the underlying issue.

**Comment by Chetic** [comment]
I discovered this plugin last week and it would be making my life 100 times easier if it wasn't for this bug. Is there any way I can help by providing data or doing grunt work? What do you need?

**Comment by groboclown** [comment]
Here's the current situation with this bug.

Every so often (I haven't found a pattern yet), the Perforce server responds to an existing, and previously working and authenticated, p4 java server connection with a "Perforce password (P4PASSWD) invalid or unset." error.

The AuthenticatedServer class contains work-arounds to deal with this situations.  If the previous connection was working, then one of these errors comes back, the class attempts a number of retries before it gives up, assuming that the password has actually changed.  This bit of work-around hackery seems to be working alright.  The big issue comes when a new AuthenticatedServer instance is created, and it has no idea whether the password is right or not; if the new instance receives an invalid password response without ever being authenticated first, it gives up - this is where all these error dialogs are coming from.

However, that's all work-arounds for the real underlying issue, which is that the server is, for some reason, responding with an unauthorized login attempt.

The main change that caused this issue to start is an attempt to always login first, rather than checking if it's needed first.  I'm going to do a bit of rework to see if this can be avoided through the p4 java API.

After that, I'll make contact with some of the Perforce support people to see if they can give any insight into what's causing the server to reject the connection.

If anyone has other ideas of paths of investigation, please chime in.

**Comment by nullexe** [comment]
For visibility, this is still occurring on 0.7.10

**Comment by groboclown** [comment]
Looks like I have a fix in place that should keep this from being quite as annoying as it has been.  It still needs testing in different circumstances - accessing parts of the depot that you don't have permission to (such as opening for edit parts you have read-only access in), and password changes making the login invalid after a valid login.  I'll publish the fix shortly.

**Comment by Chetic** [comment]
Hey @groboclown I updated this morning and it seemed to work well about the first half hour or so, but then I started getting these errors as well as being asked for the password, which won't clear the errors until I change and re-apply the plugin settings.
"Error:Problem loading pending changelists for client chetic_chetputer_main (invalid login credentials)"
"Error:Could not load your "have" revision of the files."
"Error:Could not revert files: [/home/chetic/p4/depot/bla.xml] (invalid login credentials)"
"Error:AddEditAction:[Update(EDIT_FILE:[/home/chetic/p4/depot/bla.xml]; {file=/home/chetic/p4/depot/bla.xml, changelist=2037465})]"
"Error:Problem reading server file file:///home/chetic/p4/depot/blabla.m"

**Comment by Chetic** [comment]
It _does_ seem to ask less often though...

**Comment by ghostofcain** [comment]
Weirdly enough, it's even worse than before for me. Now it's asking it every single time I touch a file, even if it's already checked out.

**Comment by groboclown** [comment]
I'm making a couple of UI changes to hopefully allow you to tweak how often you see this problem.  The first is changing how many retries before an error pops up.  The second is to change the error when this kind of error shows up.

Additionally, I'm testing out the low-level connection error trapping to attempt to add some sanity to the slow proliferation of the error checking code.  If this looks promising, I'll put out a private release (posted to Github, not the IntelliJ plugin channel) to allow some beta testing.  I'm hesitant to make it widely available, because it is directly mucking with code that has been mostly stable for many releases.

**Comment by groboclown** [comment]
I think I was able to make some progress.  The tl;dr of the matter:

Try changing your connection string to start with "nts:" (those of you using ssl connections would use "ntss:"), so that if you were connecting with `p4server:1666`, you would now use `nts:p4server:1666`.

It looks like that I subtly changed the usage pattern such that the standard, under-the-covers connection code no longer works right (It was using "OneShotServerImpl").  The way the connections are handled now should better match the usage pattern for the alternate connection code (the "NtsServerImpl", which is non-thread safe).  This change should also show a performance improvement, because it uses real server stay-alive connections.

I haven't had too much soak time using this alternate connection, but it looks promising.  Usually I'd see some login problems occasionally handled behind the scenes while refreshing the changelist view, but I'm not seeing it with this.  If this change turns out to be the right fix, then I'll change the default connection to use the new one.

**Comment by groboclown** [comment]
I haven't heard any other complaints about this issue, so I'll close it off.  You should still be able to comment to have it reopened if you're still seeing issues.
