### ISSUE TITLE
Unable to checkout file from perforce

### ISSUE THREAD

**Issue by raj-maveric** [groboclown/p4ic4idea#136]
Error:Client 'ocRakalra' can only be used from host '<>'. (error code 6239: severity 3, ref 6-95)

I am receiving the above error while checkingout of a file by using this plugin.
Steps:
right click, go to p4->Add or edit option.

client ocRakalra works for anaysing diff from perforce.
ocRakalra client works fine with perforce client for checkouts and diff analysis.

**Comment by groboclown** [comment]
This could be an issue with the host detection in the underlying Perforce API.  It doesn't always work right - sometimes with case sensitivity issues, other times with just not figuring out the hostname.

If it is the host issue, then the only way at the moment to get through this issue is to use the p4conf file, and explicitly set the P4HOST setting.  Alternatively, you can change your Perforce client to not have a host entry.

**Comment by groboclown** [comment]
Are you still having issue with the hostname?

**Comment by raj-maveric** [comment]
Hi,

I am using P4Config file now, and I have explicitly specified the hostname to reslove the issue.
And it is working fine for me.

Thanks,
Rajesh
