### ISSUE TITLE
Plugin debugging

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#137]
I've got the plugin compiling from the repository via ant from the command line, but I'm not quite clear on how to get it running in the sandbox environment.  Any additional instructions on setting up the IJ project for this and getting it running would be very helpful.

**Comment by groboclown** [comment]
Here's how I configure the project:

1. "build", "idea135" (and other "idea\d+" directories), "idea-compat", "p4java", and "plugin" directories are each their own module.  "plugin" is a plugin module, the others are Java modules.
2. "idea-compat" has dependencies on jdk 1.6, "intellij-lib/intellij/AI-135.1653844/util.jar", ".../openapi.jar", and ".../annotations.jar"
3. "idea\d+" have dependencies on idea-compat, the correct jdk (< 160 jdk 1.6, >= 160 jdk 1.8), and its intellij libraries.
4. "p4java" depends on jdk 1.6
5. "plugin" depends on your IJ sdk, p4java, mockito, junit, and _the jar output of idea-compat and idea\d+"_ (very important that it's the jars, otherwise you get all kinds of errors).

This should allow you to launch the "plugin" in debug mode.

**Comment by groboclown** [comment]
Please open a new issue if you're still having trouble debugging the plugin.  I'll close this off in a futile attempt to keep the bug log small.
