### ISSUE TITLE
Can't save any file since last update

### ISSUE THREAD

**Issue by Narthe** [groboclown/p4ic4idea#144]
Hello,
since i updated the plugin to the latest version yesterday, everytime i try to edit or save a file, i get this error : 
![p4 error 1](https://cloud.githubusercontent.com/assets/1123343/23475571/01fe4fac-fe86-11e6-8af7-f508de02a5a1.png)

The connection icon in bottom right of my IDE indicates that i'm connected to the perforce server, so does the perforce settings page :
![p4 error 1](https://cloud.githubusercontent.com/assets/1123343/23475960/22cd412e-fe87-11e6-836a-8bd20b729756.png)
(Configuration problems section is empty)
Also my p4v setup is fine i can still use it.
Refreshing the client list is unsucessful and if i add my client name manually i get another error on top of the first one telling me my files doesn't seem to be in the project

**Comment by groboclown** [comment]
Thanks for the bug report.

For each one of these disconnect errors, the plugin reports the stack trace to the idea log file.  Could you provide the stack trace that it shows (please mark out any sensitive information, like you did in the attached images)?  You can find the log quickly by clicking on **Help** -> **Show Log in Explorer**.

Though, this itself looks like a possibility for improvement - the connection error dialog could provide more details about the error.

**Comment by Narthe** [comment]
Hey, thanks for the quick reply. I'm not saying it's a bug, maybe i'm doing something wrong but everything was working fine before i update the plugin and i tried almost everything so i'm just seeking for some help.
Anyway, i tried to pick some relevant stacktrace cause there is a lot in the idea.log file. Also i realised looking at the log that the plugin doesn't ask me for my password anymore, even tho i had to everytime i started my IDE before.


[idea.txt](https://github.com/groboclown/p4ic4idea/files/812219/idea.txt)

**Comment by groboclown** [comment]
There's definitely one issue here - the connection isn't recognizing this as a password problem:

```
com.perforce.p4java.exception.AuthenticationFailedException: Your session has expired, please login again.
    at com.perforce.p4java.impl.mapbased.server.Server.createExceptionFromMessage(Server.java:4062)
    at com.perforce.p4java.impl.mapbased.server.Server.handleErrorStr(Server.java:4925)
    at com.perforce.p4java.impl.mapbased.server.Server.getClient(Server.java:2339)
    at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.loadClient(ClientExec.java:251)
...
net.groboclown.idea.p4ic.server.exceptions.P4UnknownLoginException: Your session has expired, please login again.
    at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:266)
    at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:149)
    at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.retry(ServerRunner.java:423)
    at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:176)
    at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:141)
    at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:263)
    at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithClient(ClientExec.java:147)
    at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getClient(P4Exec2.java:135)
    at net.groboclown.idea.p4ic.v2.server.cache.sync.WorkspaceServerCacheSync.innerLoadServerCache(WorkspaceServerCacheSync.java:391)
```

This problem comes from the plugin attempting to use the session stored in the auth ticket file, which the server reports as being expired.

The other issue, regarding the client roots, comes from the lack of a loaded workspace.

Try adding the "requires password" component.  This will force the configuration to not look a the auth ticket file.

**Comment by Narthe** [comment]
Adding the require password component prevents me from clicking Apply or OK, it just does nothing.
I tried doing a fresh install of the IDE + perforce plugin and now the Perfoce configuration page doesn't show up...
![empty perforce page](https://cloud.githubusercontent.com/assets/1123343/23522793/5c57a5a8-ff52-11e6-8605-7256847749c7.png)
[log.txt](https://github.com/groboclown/p4ic4idea/files/814856/log.txt)

**Comment by groboclown** [comment]
The "OK" and "Apply" buttons seem to have a strange state.  The IDE is supposed to handle enabling and disabling them, but it doesn't seem to check the state right.  I've noticed that if you press one of the refresh buttons it forces the IDE to set those buttons to the correct state.

Your log file included some great information - specifically, for this error:

```
java.lang.IllegalArgumentException: Server config {P4TRUST=C:\Users\youruser\dev\test, P4PASSWD=<no plaintext password>, P4PORT=adress-to-my-perforce-server:2976, P4TICKETS=(no value), P4USER=youruser, Server Fingerprint=(no value)} does not match data config MultipleDataPart(file://C:/Users/youruser/dev/test)
```

which explains why you're having trouble with loading the client names.  This was a sanity check to ensure the server connection object matches the configuration object, and we tripped it.  It looks like the code is either generating the wrong server connection, or it's not forcing the configuration to reload itself first.

I'm also guessing that this problem is causing the horrible slowdown.  I'll investigate this more and see what I come up with.

**Comment by groboclown** [comment]
I'm working through several potential bugs, to see if any of them are related to this issue.

The best work around for loading the client names, right now, is to type in some text (doesn't matter what) into the client name field.  That may cause a problem if the IDE doesn't already know your password.  I'm going to keep working on this.

**Comment by Narthe** [comment]
Thanks for the update ;)

**Comment by groboclown** [comment]
Turned out that that specific problem was simple, but it uncovered a few others that were harder to tackle.

I have a new release out that should fix up many of these problems.

https://github.com/groboclown/p4ic4idea/releases/tag/v0.8.4-beta.2

There's still an issue with the password prompting, though.  If you are prompted for the password, you need to manually refresh the server listing, either by viewing the configuration UI again, or by using the status bar widget.

**Comment by groboclown** [comment]
Another beta release.  It's creeping closer to being ready.

https://github.com/groboclown/p4ic4idea/releases/tag/v0.8.4-beta.3

**Comment by groboclown** [comment]
0.8.4 is out.  This issue should be fixed in the release.  Please reopen if you are still seeing the problem.
