### ISSUE TITLE
"Name" and "Comment" is concatenated as the Description

### ISSUE THREAD

**Issue by thsaravana** [groboclown/p4ic4idea#91]
I created a new changlist with Name="Memory Issue Changes". Now during 'Submit' of this changelist, in the "Commit changes..." dialog I added Commit Message="Making the following changes ... so on...". Now when I Submit it and reopen this in the P4VClient and look at the Description of the Changelist, I see the following in the description:

Memory Issue Changes
Making the following changes ... so on...

Is this how it's supposed to be? I just want the Comment in the description and not the NAME of the changelist.

**Comment by groboclown** [comment]
This was a compromise between the two systems, where Perforce only has a long-form comment, while IntelliJ has the name + comment.

This could definitely use more smarts about when to include the name of the IntelliJ change vs. just using the comment.

**Comment by groboclown** [comment]
I've fixed the code so that now only the comment part of the IDEA changelist is used to set the p4 changelist description, but if that's empty it uses the name of the IDEA changelist; this seems to match the behavior of the "submit" action.

I've added in a user flag to switch back to the old behavior if you prefer that one.
